############################################################
# Dockerfile to build FASTQC container images
# Based on Ubuntu
# adapt from
# https://github.com/GenomicParisCentre/dockerfiles/blob/master/fastqc/fastqc-0.11.3/Dockerfile
############################################################

# Set the base image to Ubuntu
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER QUAN YU <lsiqyu@nus.edu.sg>

# Update the repository sources list
RUN apt-get update && apt-get install --yes openjdk-7-jre-headless perl unzip wget


